/* autogenerated by Processing revision 1286 on 2025-10-22 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class SpaceGame_el extends PApplet {

// El Jacobsen | 17 September 2025 | Space Game


Spaceship fih;
ArrayList<Rock> corals = new ArrayList<Rock>();
ArrayList<Laser> hydros = new ArrayList<Laser>();
ArrayList<Star> stars = new ArrayList<Star>();
ArrayList<PowerUp> powups = new ArrayList<PowerUp>();
Timer coralTimer, puTimer, levelTimer;
int score, rocksPassed;
boolean play;
PImage start, over;
SoundFile pew, blowup, space, gend;


 public void setup() {
  /* size commented out by preprocessor */;
  pew = new SoundFile(this, "retroLaser.mp3");
  space = new SoundFile(this, "spaceSound.mp3");
  space.play();
  blowup = new SoundFile(this, "retroExplode.mp3");
  gend = new SoundFile(this, "endGame.mp3");
  fih = new Spaceship();
  score = 0;
  rocksPassed = 0;
  play = false;

  //levelTimer = new Timer (30000);
  //levelTimer.start();

  coralTimer = new Timer(1300);
  coralTimer.start();

  puTimer = new Timer(10000);
  puTimer.start();
}


 public void draw() {
  start = loadImage ("startGame.png");
  over = loadImage("endGame.png");

  if (!play) {
    startScreen();
  } else {
    background(3, 3, 22);

    //check levels
    // if (level == 1) {
    //}

    //Display stars
    stars.add(new Star());
    for (int i = 0; i < stars.size(); i++) {
      Star star = stars.get(i);
      star.display();
      star.move();
      if (star.reachedBottom()) {
        stars.remove(star);
        i--;
      }
      println("Stars: " + stars.size());
    }
    //Distrubuting PowerUps on Timer
    if (puTimer.isFinished()) {
      powups.add(new PowerUp());
      puTimer.start();
    }

    // Display of powerups
    for (int i = 0; i < powups.size(); i++) {
      PowerUp pu = powups.get(i);
      pu.display();
      pu.move();

      if (pu.intersect(fih)) {
        powups.remove(pu);

        if (pu.type == 't') {
          fih.turretCount++;
          if (fih.turretCount>5) {
            fih.turretCount = 5;
          }
        } else if (pu.type == 'h') {
          fih.health+=50;
          if (fih.health >50) {
            fih.health = 100;
          }
        } else if (pu.type == 'a') {
          fih.laserCount+=100;
        }
      }
    }

    // Distrubution of Rocks on Timer
    if (coralTimer.isFinished()) {
      corals.add(new Rock());
      coralTimer.start();
    }

    //Display of rocks
    for (int i = 0; i < corals.size(); i++) {
      Rock coral = corals.get(i);
      coral.display();

      if (fih.intersect(coral)) {
        corals.remove(coral);
        score+=coral.diam;
        fih.health -= 10;
      }

      coral.move();
      if (coral.reachedBottom()) {
        rocksPassed++;
        corals.remove(coral);
        i--;
      }
      println("Corals: " + corals.size());
    }

    //Display of lasers
    for (int i = 0; i < hydros.size(); i++) {
      Laser hydro = hydros.get(i);
      for (int j =0; j<corals.size(); j++) {
        Rock c = corals.get(j);
        if (hydro.intersect(c)) {
          hydros.remove(hydro);

          c.diam -= 40;
          c.broken = true;

          if (c.diam<40) {
            corals.remove(c);
            blowup.play();
          }
          score+=5;
        }
      }

      hydro.display();
      hydro.move();
      if (hydro.reachedTop()) {
        hydros.remove(hydro);
        i--;
      }
    }
    println("Hydros: " + hydros.size());
    if (pew.isPlaying()) {
      pew.stop();
    } else {
      play = true;
    }
    fih.display();
    fih.move(mouseX, mouseY);

    infoPanel();


    if (fih.health <1 ||  rocksPassed >20) {
      gameOver();
    }
  }
}

 public void startScreen () {
  background(start);

  textAlign(CENTER);
  textSize(35);
  fill(255);
  text("SPACE GAME", width/2, 150);


  textAlign(CENTER);
  textSize (30);
  fill(255);
  text("EL JACOBSEN 2A", width/2, 250);
  text("CLICK MOUSE TO START", width/2, 300);
  if (mousePressed) {
    play = true;
    space.stop();
  }
}

 public void gameOver () {
  background(over);
  textAlign(CENTER);
  textSize(35);
  fill(255);
  text("GAME OVER, SCORE: " + score, width/2, 300);
  noLoop();
  gend.play();
}

 public void mousePressed() {
  if (fih.fire()) {
    hydros.add(new Laser(fih.x, fih.y));
    fih.laserCount--;
    pew.play();
  }
}

 public void infoPanel() {
  //healthbar
  fill(255);
  rect(55, 770, 106, 10);
  fill(75, 0, 0);
  rect(55, 770, fih.health, 8);

  textAlign(CORNER);
  textSize(20);
  fill(255);
  text("SCORE: " + score, 55, 800);
  text("AMMO: " + fih.laserCount, 55, 830);
  text("ROCKS PASSED: " + rocksPassed, 55, 860);
}

class Laser {

  //Member Variables
  int x, y, w, h, speed;
  PImage hydro;

  //Constructor
  Laser (int x, int y) {
    this.x = x;
    this.y = y;
    w = 4;
    h = 10;
    speed = 10;
    hydro = loadImage("laser.png");
  }

  //Member Methods
   public void display() {
    imageMode(CENTER);
    image(hydro, x, y, w, h);
  }

   public void move() {
    y = y - speed;
  }

   public boolean reachedTop () {
    if (y<0-10) {
      return true;
    } else {
      return false;
    }
  }


   public boolean intersect(Rock c) {
    float d = dist( x, y, c.x, c.y);
    if (d<40) {
      return true;
    } else {
      return false;
    }
  }
}
class PowerUp {
  //Member Variables
  int x, y, w, speed;
  char type;
  PImage r1;
  int c1;

  //Constructor
  PowerUp() {
    x = PApplet.parseInt(random(width));
    y = -100;
    w = 100;
    speed = PApplet.parseInt(random(1, 4));

    if (random(10)>6.6f) {
      r1 = loadImage ("ammoRefill.png");
      type = 'a'; //AMMO

    } else if (random(10)>5.0f) {
      r1 = loadImage ("healthRefill.png");
      type = 'h'; //HEALTH

    } else {
      r1 = loadImage ("newTurret.png");
      type = 't'; //FIRING LASER INCREASE

    }
  }

  //Member Methods
   public void display() {
    imageMode(CENTER);
    image(r1, x, y);
  }

   public void move() {
    y = y + speed;
  }

   public boolean reachedBottom () {
    if (y>height + 100) {
      return true;
    } else {
      return false;
    }
  }

   public boolean intersect(Spaceship s) {
    float d = dist(x, y, s.x, s.y);
    if (d<40) {
      return true;
    } else {
      return false;
    }
  }
}
class Rock {
  //Member Variables
  int x, y, diam, speed, c;
  PImage r1, r2;
  boolean broken;

  //Constructor
  Rock() {
    x = PApplet.parseInt(random(width));
    y = -100;
    diam = PApplet.parseInt(random(50, 150));
    speed = PApplet.parseInt(random(1, 6));
    if (random(10)>6.6f) {
      r1 = loadImage ("coral3.png");
      r2 = loadImage("coral3break.png");
      broken = false;
    } else if (random(10)>5.0f) {
      r1 = loadImage ("coral2.png");
      r2 = loadImage ("coral2break.png");
      broken = false;
    } else {
      r1 = loadImage ("coral1.png");
      r2 = loadImage ("coral1.png");
      broken = false;
    }
  }

  //Member Methods
   public void display() {

    if (broken == false) {
      imageMode(CENTER);
      r1.resize(diam, diam);
      image(r1, x, y);
    } else {
      imageMode(CENTER);
      r2.resize(diam, diam);
      image(r2, x, y);
    }
  }

   public void move() {
    y = y + speed;
  }

   public boolean reachedBottom () {
    if (y>height + 100) {
      return true;
    } else {
      return false;
    }
  }
}
class Spaceship {
  //Member Variables
  int x, y, w, health, laserCount, turretCount;
  PImage ship;

  //Constructor
  Spaceship() {
    x = width/2;
    y = height/2;
    w = 100;
    health = 100;
    laserCount = 200;
    turretCount = 1;
    ship = loadImage ("fihy.png");
  }

  //Member Methods
   public void display() {
    image(ship, x, y);
    imageMode(CENTER);
  }

   public void move(int x, int y) {
    this.x = x;
    this.y = y;
  }

   public boolean fire() {
    if (laserCount>0) {
      return true;
    } else {
      return false;
    }
  }

   public boolean intersect(Rock c) {
    float d = dist(x, y, c.x, c.y);
    if (d<40) {
      return true;
    } else {
      return false;
    }
  }
}
class Star {
  //Member Variables
  int x, y, w, speed;

  //Constructor
  Star () {
    x = PApplet.parseInt(random(width));
    y = -10;
    w = PApplet.parseInt(random(1, 4));
    speed = PApplet.parseInt(random(1, 4));
  }
  //Member Methods
   public void display() {
    fill(random(225, 255));
    ellipse(x, y, w, w);
  }

   public void move() {
    y+=speed;
  }

   public boolean reachedBottom () {
    if (y>height +10) {
      return true;
    } else {
      return false;
    }
  }
}
//Daniel Shiffman

class Timer {
  
  int savedTime; // When Timer started
  int totalTime; // How long Timer should last

  Timer(int tempTotalTime) {
    totalTime = tempTotalTime;
  }

  // Starting the timer
   public void start() {
    // When the timer starts it stores the current time in milliseconds.
    savedTime = millis();
  }

  // The function isFinished() returns true if 5,000 ms have passed. 
  // The work of the timer is farmed out to this method.
   public boolean isFinished() { 
    // Check how much time has passed
    int passedTime = millis()- savedTime;
    if (passedTime > totalTime) {
      return true;
    } else {
      return false;
    }
  }
}


  public void settings() { size(800, 900); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "SpaceGame_el" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
